---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/sts2/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/src
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp -R src/* $DEPLOYPATH/src/
